# Generated by Django 4.2 on 2024-06-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_inici_vote_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='nom_usuari',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='valoracio',
        ),
    ]
