# Generated by Django 4.2 on 2024-06-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_vote_nom_usuari_remove_vote_valoracio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='inici',
            new_name='data',
        ),
    ]
