# Generated by Django 4.2 on 2024-06-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_inici_vote_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
