# Generated by Django 4.2 on 2024-06-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_partit_detalls_partit_inici_partit_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lliga',
            old_name='numero_d_equips',
            new_name='numero_equips',
        ),
    ]
