# Generated by Django 4.2 on 2024-06-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0004_rename_numero_d_equips_lliga_numero_equips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='estadistiques',
        ),
    ]
