# Generated by Django 4.2 on 2024-06-27 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0005_remove_jugador_estadistiques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lliga',
            name='numero_equips',
        ),
        migrations.AddField(
            model_name='lliga',
            name='data_final',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lliga',
            name='data_inici',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
