# Generated by Django 4.2 on 2024-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0006_remove_lliga_numero_equips_lliga_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default='Girona', max_length=255),
            preserve_default=False,
        ),
    ]
